name: ios_f_n_nesine_3221
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  share_plus: ^10.1.4
  image_picker: ^1.1.2

  # state management
  flutter_bloc: ^9.0.0

  # local data saving
  shared_preferences: ^2.5.2
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.5
  onesignal_flutter: ^5.3.0
  appsflyer_sdk: ^6.15.2
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.4.0
  app_tracking_transparency: ^2.0.6
  app_set_id: ^1.2.1
  flutter_asa_attribution: ^1.0.0
  loading_animation_widget: ^1.3.0

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/l1.png
  ios_content_mode: scaleAspectFill


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.4
  flutter_timer_countdown: ^1.0.7
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/onboarding/
    - assets/images/types_sport/
